model:
  name: chinese-clip-vit-base-patch16
  backend: onnxruntime
  embedding_dimensions: 512
  batch_size: 64
  device: cpu
  onnx_path: ${KVAI_MODEL_PATH}
  tokenizer_path: ${KVAI_TOKENIZER_PATH}
